<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$required = '';
if ($block->hasRequiredOptions()) {
    $required = ' data-hasrequired="' . __('* Required Fields') . '"';
}
?>
<?php
$_product = $block->getProduct();
$helper = $this->helper('TargetTraining\CustomOptions\Helper\Data');
?>
<?php if(!$helper->getAttributeSet($_product) || $helper->getCustomOption($_product)) :?>
<div class="product-options-wrapper" id="product-options-wrapper"<?= /* @escapeNotVerified */ $required ?>>
    <div class="fieldset" tabindex="0">
        <?= $block->getChildHtml('', true) ?>
    </div>
</div>
<?php endif;?>