<?php
/**
 * @var $block TargetTraining\EventFinder\Block\Widget
 */
?>

<div class="section section--course-finder">
    <div class="course-finder--content">
        <div class="course-finder--header">
            <h2>
                Course Finder
                <span>Or see all our <a href="<?php echo $block->escapeUrl($block->getFormAction()) ?>">training courses <span class="hidden-mobile">here</span></a></span>
            </h2>
        </div>
        <div class="course-finder--body">
            <form id="form-find-courses" class="form" action="<?php echo $block->escapeUrl($block->getFormAction()) ?>" id="" method="post">
                <div class="fieldset">
                    <div class="field location">
                        <label><?php echo __('Select Location') ?></label>
                        <div class="control">
                            <select class="select" name="location" id="location">
                                <option value="0"><?php echo __('Select Location') ?></option>
                                <?php foreach ($block->getAvailableLocations() as $location): ?>
                                    <option value="<?php echo $location['value'] ?>"><?php echo $location['label'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="field type">
                        <label><?php echo __('Select Course Type') ?></label>
                        <div class="control">
                            <select class="select" name="type" id="type">
                                <option value="0"><?php echo __('Select Course Type') ?></option>
                                <?php foreach ($block->getAvailableTypes() as $type): ?>
                                    <option value="<?php echo $type['value'] ?>"><?php echo $type['label'] ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" id="find-courses" title="" class="action submit primary">
                            <span><?php echo $block->escapeHtml(__('Find Courses')) ?></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/javascript">
    require(['jquery'], function ($){
        $("#find-courses").click(function(e) {
            e.preventDefault();
            var param = "<?= $block->getFormAction() ?>"+"?location="+jQuery('#location').val()+"&type="+jQuery('#type').val();
            $('#form-find-courses').attr('action', param).submit();
        });
    });
</script>
