<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$helperDate = $this->helper('TargetTraining\Ticket\Helper\Data');
$currentCate = $this->helper('TargetTraining\CatalogCategory\Helper\Data')->getCurrentCategory();
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if neededspaces-remaining
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <!-- add date -->
                    <?php if ($_product->getDate()): ?>
                        <div class="date calendar">
                            <span class="day"><?= date('M', strtotime($_product->getDate())); ?></span>
                            <span class="month"><?= date('d', strtotime($_product->getDate())); ?></span>
                        </div>
                    <?php endif;?>

                    <div class="product details product-item-details">

                        <?php if ($currentCate): ?>
                            <?php if (!is_null($currentCate->getCourseCategories()) && $currentCate->getCourseCategories()): ?>
                                <div class="product-image">
                                    <?php
                                    $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
                                        ->init($_product, 'product_base_image')
                                        ->constrainOnly(TRUE)
                                        ->keepAspectRatio(TRUE)
                                        ->keepTransparency(TRUE)
                                        ->keepFrame(FALSE)
                                        ->getUrl();
                                    ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"><img src="<?php echo $imageUrl;?>" class="view-product-image" alt="<?php echo $_product->getName()?>"></a>
                                    <!-- add location-->
                                    <div class="location">
                                        <span class="location-title"><?= $_product->getAttributeText('course_location');?></span>
                                    </div>
                                       <?php if($_product->getIsinhousecourse() == "1"){ ?>

                                     <div class="inhouseopt">
                                        <span class="inhouse-title"> In-House Option</span>
                                    </div>
                               <?php } ?>
                                </div>
                             
                          
                            <?php endif;?>
                        <?php endif;?>

                        <div class="product-item-details-top">
                            <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?php /*
                            <div class="spaces-remaining">
                                <span class="count<?php if(intval($helperDate->getQty($_product->getId()) < 3)){ echo ' text-red';}?>"><?php echo intval($helperDate->getQty($_product->getId())); ?></span>
                                <span class="label"><?= __('spaces remaining') ?></span>
                            </div>
                            */ ?>
                            <!-- end add location-->
                            <div class="short_description">
                                <span><?= $_product->getShortDescription() ?></span>
                            </div>
                        </div>

                        <?php if ($currentCate): ?>
                            <?php if (!is_null($currentCate->getCourseCategories()) && !$currentCate->getCourseCategories()): ?>
                                <div class="product-image">
                                    <?php
                                    $imageUrl = $this->helper('Magento\Catalog\Helper\Image')
                                        ->init($_product, 'product_base_image')
                                        ->constrainOnly(TRUE)
                                        ->keepAspectRatio(TRUE)
                                        ->keepTransparency(TRUE)
                                        ->keepFrame(FALSE)
                                        ->getUrl();
                                    ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>"><img src="<?php echo $imageUrl;?>" class="view-product-image" alt="<?php echo $_product->getName()?>"></a>
                                </div>
                            <?php endif;?>
                        <?php endif;?>

                        <div class="product-item-details-bottom">
                            <div class="price-wrap">
                                <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                                <?php if ($currentCate): ?>
                                    <?php if (!is_null($currentCate->getCourseCategories()) && !$currentCate->getCourseCategories()): ?>
                                        <span class="price-suffix">excluding VAT</span>
                                    <?php else: ?>
                                        <span class="price-suffix">per person, excluding VAT.</span>
                                    <?php endif;?>
                                <?php else:?>
                                    <span class="price-suffix">per person, excluding VAT.</span>
                                <?php endif;?>
                                <?= $block->getProductDetailsHtml($_product) ?>

                                <div class="product-item-inner">
                                    <?php if ($showDescription):?>
                                        <div class="product description product-item-description">
                                            <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($currentCate): ?>
                                <?php if (!is_null($currentCate->getCourseCategories()) && !$currentCate->getCourseCategories()): ?>
                                    <div class="product-item-details-actions primary">
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to basket')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= /* @escapeNotVerified */ __('Add to basket') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->isAvailable()): ?>
                                                <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                <?php else: ?>
                                    <div class="product-item-details-actions primary">
                                        <?php if (!is_null($currentCate->getCourseCategories()) && $currentCate->getCourseCategories()) : ?>
                                            <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                               class="action primary more"><?= /* @escapeNotVerified */ __('View Course') ?></a>
                                        <?php else: ?>
                                            <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                               class="action primary more"><?= /* @escapeNotVerified */ __('Dates, Info & Book') ?></a>
                                        <?php endif; ?>
                                    </div>
                                <?php endif;?>
                            <?php else: ?>
                                <div class="product-item-details-actions primary">
                                    <?php if ($currentCate && !is_null($currentCate->getCourseCategories()) && $currentCate->getCourseCategories()) : ?>
                                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                           class="action primary more"><?= /* @escapeNotVerified */ __('View Course') ?></a>
                                    <?php else: ?>
                                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                           class="action primary more"><?= /* @escapeNotVerified */ __('Dates, Info & Book') ?></a>
                                    <?php endif; ?>
                                </div>
                            <?php endif;?>
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
