<?php $objectManager = \Magento\Framework\App\ObjectManager::getInstance() ?>
<?php $posts = $objectManager->create('FishPig\WordPress\Model\ResourceModel\Post\Collection')
	->addPostTypeFilter('post')
	->setOrderByPostDate()
	->addIsViewableFilter()
	->setPageSize(3)
	->load(); ?>
<?php if (count($posts) > 0): ?>
	<ul>
		<?php foreach($posts as $post): ?>
			<li>
        <?php echo $post->getPostDate() ?>
				<a href="<?php echo $post->getUrl() ?>"><?php echo $this->escapeHtml($post->getPostTitle()) ?></a>
				<?php if ($image = $post->getFeaturedImage()): ?>
					<a href="<?php echo $post->getUrl() ?>">
						<img src="<?php echo $image->getAvailableImage() ?>" src="<?php echo $this->escapeHtml($post->getPostTitle()) ?>" />
					</a>
				<?php endif; ?>
				<p><?php echo $post->getPostExcerpt(40) ?></p></li>
		<?php endforeach; ?>
	</ul>
<?php endif; ?>
