<?php
    $_productCollection = $block->getCollectionProduct();
    $_helper = $this->helper('Magento\Catalog\Helper\Output');
    $helperDate = $this->helper('TargetTraining\Ticket\Helper\Data')
?>
<?php if($_productCollection->getSize()):?>
<div class="block related">
    <div class="block-title title">
        <strong role="heading" aria-level="2"><?= __('featured courses') ?></strong>
    </div>

    <div class="products wrapper grid products-grid products-related" >
        <ol class="products list items product-items">
            <?php foreach ($_productCollection as $_item): ?>
                <li class="item product product-item">
                    <div class="product details product-item-details">
                        <div class="row">
                            <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= $_item->getProductUrl() ?>" >
                                    <?= $block->escapeHtml($_item->getName()) ?></a>
                            </strong>
                        </div>

                        <div class="row">
                            <a href="<?= /* @escapeNotVerified */ $_item->getProductUrl() ?>"><?= __('Read more') ?></a>
                                <div class="actions-primary">
                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                        <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('Book') ?>">
                                            <span><?= /* @escapeNotVerified */ __('Book') ?></span>
                                        </button>
                                    <?php else: ?>
                                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                        ?>
                                        <button class="action tocart primary"
                                                data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                type="button" title="<?= /* @escapeNotVerified */ __('Book') ?>">
                                            <span><?= /* @escapeNotVerified */ __('Book') ?></span>
                                        </button>
                                    <?php endif; ?>
                                </div>
                        </div>

                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
</div>
<?php endif; ?>