<?php
/**
 * Copyright © 2015 Magenest. All rights reserved.
 * See COPYING.txt for license details.
 *
 *
 * Magenest_Ticket extension
 * NOTICE OF LICENSE
 *
 * @category  Magenest
 * @package   Magenest_Ticket
 * @author ThaoPV <thaopw@gmail.com>
 */
?>
<?php
    /** @var  Magenest\Ticket\Block\Adminhtml\Catalog\Product\Edit\Tab\Event $block */
    echo /* @escapeNotVerified */ $block->getTabsHtml();
?>
<div id="event_tab_content"></div>