<?php
/**
 * @category Mageants AllSlider
 * @package Mageants_AllSlider
 * @copyright Copyright (c) 2017 Mageants
 * @author Mageants Team <support@mageants.com>
 */
use Magento\Framework\App\Action\Action;

?>
<?php
/**
 * Slider list template
 *
 * @var $block \Mageants\AllSlider\Block\Product\ProductList
 */
?>
<div class="rcontainer-fluid">
<?php $getAllSliders = $block->getAllSliders(); ?>
<?php $_helper = $block->output(); ?>
<?php
$viewMode = 'grid';
$image = 'category_page_grid';
$showDescription = false;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$pos = $block->getPositioned();
$position = '';
$limit = $block->getProductLimit();
?>
<?php $count = 1; ?>
<?php foreach ($getAllSliders as $getAllSlider): ?>
    <div class="rcontainer">        
        <?php if ($getAllSlider->getIsDisplayTitle() && $getAllSlider->getTitle()): ?>
            <h2 class="mageants-block-title">
                <span><?= /* @noEscape */ __($getAllSlider->getTitle()); ?></span>
            </h2>
        <?php endif; ?>        
        <?php $productIds = explode(',', $getAllSlider->getProductIds()); ?>
        <?php if ($productIds > 1): ?>
            <div class="wrapper <?= /* @noEscape */ $viewMode; ?> products-<?= /* @noEscape */ $viewMode; ?>">
                <?php $iterator = 1; ?>
                <div class="list items product-items owl-carousel owl-theme" 
                id="owl-demo<?= /* @noEscape */ $count; ?>">
                    <?php $prdCount = 0; ?>
                    <?php foreach ($productIds as $productId): ?>
                        <?php $_product = $block->getLoadProduct($productId); ?>
                        <?php if ($_product->getStatus() != 1 || $_product->getVisibility() != 4):?>
                            <?php continue; ?>
                        <?php endif; ?>                        
                        <?php $prdCount++; ?>
                        <?php if ($prdCount > $limit): ?>
                            <?php break; ?>
                        <?php endif; ?>
                        <div class="item product">
                            <div class="product-item-infos item" data-container="product-grid">
                                <?php
                                $productImage = $block->getImage($_product, $image);
                                if ($pos != null) {
                                    $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                        . 'top:' . $productImage->getHeight() . 'px;"';
                                }
                                ?>
                                <?php // Product Image ?>
                                <a href="<?= /* @noEscape */ $_product->getProductUrl() ?>" 
                                    class="product photo product-item-photo" tabindex="-1">
                                    <?= /* @noEscape */ $productImage->toHtml(); ?>
                                </a>
                                <div class="product details product-item-details">
                                    <?php $_productNameStripped = $block
                                    ->stripTags($_product->getName(), null, true); ?>
                                    <strong class="product name product-item-name">
                                        <a class="product-item-link"
                                           href="<?= /* @noEscape */
                                            $_product->getProductUrl() ?>">
                                            <?= /* @noEscape */
                                            $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                        </a>
                                    </strong>
                                    <?php if ($block->getIsEnabledReview()): ?>
                                        <?= /* @noEscape */ $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                    <?php endif; ?>
                                    <?php if ($block->getIsEnabledPrice()): ?>
                                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                    <?php endif; ?>
                                    <div class="product-item-inners">
                                        <?php if ($block->getIsEnabledAddtocart()
                                        || $block->getIsEnabledWishlist()
                                        || $block->getIsEnabledCompare()): ?>
                                            <div class="product actions product-item-actions">
                                                <?php if ($block->getIsEnabledAddtocart()): ?>
                                                    <div class="actions-primary">
                                                        <?php if ($_product->isSaleable()): ?>
                                                            <?php $postParams = $block
                                                            ->getAddToCartPostParams($_product); ?>
                                                            <form data-role="tocart-form" 
                                                            action="<?= /* @noEscape */ $postParams['action']; ?>" 
                                                            method="post">
                                                                <input type="hidden" 
                                                                 name="product" 
                                                                 value="<?= /* @noEscape */
                                                                    $postParams['data']['product']; ?>">
                                                                <input 
                                                                type="hidden" 
                                                                name="<?= /* @noEscape */
                                                                Action::PARAM_NAME_URL_ENCODED; ?>"
                                                            value="<?= /* @noEscape */
                                                            $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                                <?= /* @noEscape */ $block->getBlockHtml('formkey')?>
                                                                <button type="submit"
                                                                  title="<?= /* @noEscape */
                                                                    $block->escapeHtml(__('Add to Cart')); ?>"
                                                                  class="action tocart primary">
                                                                    <span><?= /* @noEscape */ __('Add to Cart') ?>
                                                                    </span>
                                                                </button>
                                                            </form>
                                                        <?php else: ?>
                                                            <?php if ($_product->getIsSalable()): ?>
                                                                <div class="stock available">
                                                                <span><?= /* @noEscape */ __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable">
                                                                <span><?= /* @noEscape */ __('Out of stock') ?>
                                                                </span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                                <?php if ($block->getIsEnabledWishlist()
                                                || $block->getIsEnabledCompare()): ?>
                                                    <div data-role="add-to-links" class="actions-secondary">
                                                        <?php if ($block->wishlistHelper()->isAllow()
                                                        && $block->getIsEnabledWishlist()): ?>
                                                            <a href="#" 
                                                               class="action towishlist"
                                                               title="<?= /* @noEscape */
                                                                $block->escapeHtml(__('Add to Wishlist')); ?>"
                                                               aria-label="<?= /* @noEscape */
                                                                $block->escapeHtml(__('Add to Wishlist')); ?>"
                                                               data-post='<?= /* @noEscape */
                                                                $block->getAddToWishlistParams($_product); ?>'
                                                               data-action="add-to-wishlist"
                                                               role="button">
                                                               <span><?= /* @noEscape */ __('Add to Wishlist') ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                        <?php if ($block->getIsEnabledCompare()): ?>
                                                            <?php $compareHelper = $block->compareHelper();
                                                            ?>
                                                <a href="#" class="action tocompare"
                                                   title="<?= /* @noEscape */
                                                    $block->escapeHtml(__('Add to Compare')); ?>"
                                                   aria-label="<?= /* @noEscape */
                                                    $block->escapeHtml(__('Add to Compare')); ?>"
                                                   data-post='<?= /* @noEscape */
                                                    $compareHelper->getPostDataParams($_product); ?>'
                                                   role="button">
                                                                <span><?= /* @noEscape */ __('Add to Compare') ?></span>
                                                            </a>
                                                        <?php endif; ?>
                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <script>
        require(['jquery', 'owl_carousel'], function($){
            $(document).ready(function() { 
                $("#owl-demo<?= /* @noEscape */ $count; ?>").owlCarousel({         
                    autoPlay: false, //Set AutoPlay to 3 seconds         
                    items : '<?= /* @noEscape */ $block->getItems(); ?>',
                    margin: 10,
                    itemsDesktop : [1199,4],
                    itemsDesktopSmall : [979,3],
                    itemsTablet: [768,2],
                    itemsMobile : [479,1],
                    navigation:true,
                    pagination:false,
                    slideSpeed:'<?= /* @noEscape */ $block->getSlideShowSpeed(); ?>'
                });
                $(window).resize( function(){
                    if($(window).innerWidth()>1024){
                        $(".owl-carousel").width($(".owl-carousel").parents('div').innerWidth());
                    }    
                    else{
                        $(".owl-carousel").width($(window).innerWidth());
                    }
                    
                })
                if($(window).innerWidth()>1024){
                    $(".owl-carousel").width($(".owl-carousel").parents('div').innerWidth());
                }    
                else{
                    $(".owl-carousel").width($(window).innerWidth());
                }                
            });        
        });    
    </script>
    <?php $count++; ?>
<?php endforeach; ?>
</div>
