<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= /* @escapeNotVerified */ __('Sort by:') ?></label>
    <?php
    $currentUrl = ($this->getUrl('*/*/*', ['_use_rewrite' => true]));
    $currentCate = $this->helper('TargetTraining\CatalogCategory\Helper\Data')->getCurrentCategory();
    ?>
    <?php if ($currentCate): ?>
        <?php if (!is_null($currentCate->getCourseCategories()) && !$currentCate->getCourseCategories()): ?>
            <a href="<?php echo $currentUrl. "?product_list_order=price"; ?>"><?= __('Cost') ?></a>
        <?php else: ?>
            <a href="<?php echo $currentUrl. "?product_list_order=date"; ?>"><?= __('Date') ?></a>
            <a href="<?php echo $currentUrl. "?product_list_order=name"; ?>"><?= __('Course') ?></a>
            <a href="<?php echo $currentUrl. "?product_list_order=quantity_and_stock_status"; ?>"><?= __('Spaces Available') ?></a>
        <?php endif;?>
    <?php else:?>
        <a href="<?php echo $currentUrl. "?product_list_order=date"; ?>"><?= __('Date') ?></a>
        <a href="<?php echo $currentUrl. "?product_list_order=name"; ?>"><?= __('Course') ?></a>
        <a href="<?php echo $currentUrl. "?product_list_order=quantity_and_stock_status"; ?>"><?= __('Spaces Available') ?></a>
    <?php endif;?>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <option value="<?= /* @escapeNotVerified */ $_key ?>"
                <?php if ($block->isOrderCurrent($_key)): ?>
                    selected="selected"
                <?php endif; ?>
            >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?= /* @escapeNotVerified */ __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?= /* @escapeNotVerified */ __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a title="<?= /* @escapeNotVerified */ __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?= /* @escapeNotVerified */ __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?>
</div>
