<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
    $_product = $block->getProduct();
    $helper = $this->helper('TargetTraining\CustomOptions\Helper\Data');
?>
<?php
$attributeSetName = $this->helper('TargetTraining\CatalogCategory\Helper\Data')->getAttributeSetName();
if ($attributeSetName && $attributeSetName == 'Course') {
    $buttonTitle = __('Book now');
} else {
    $buttonTitle = __('Add to basket');
}
?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <input type="hidden" name="attendees" value="">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Qty') ?></span></label>
            <div class="control">
                <input type="number"
                       name="qty"
                       id="qty"
                       maxlength="12"
                       value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                       title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                       data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
        </div>
        <?php endif; ?>
        <?php if($helper->getAttributeSet($_product) && !$helper->getCustomOption($_product)) :?>
            <a class="action primary" href="/contact"> Contact Us </a>
        <?php else:?>
            <div class="actions">
                <?php if ($attributeSetName && $attributeSetName == 'Course') : ?>
                    <button type="button" class="action primary tocart fake-book-now"><span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span></button>
                <?php endif;?>
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button">
                    <span><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        <?php endif;?>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php if (!$block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "catalogAddToCart": {
                "bindSubmit": false
            }
        }
    }
</script>
<?php endif; ?>

<div style="display: none">
    <div id="add-attendees-popup" class="add-attendees-popup sys_add_attendee_popup">

        <div class="attendees-popup-content">

            <div class="attendees-title"><?php echo __('Add Attendees')?></div>
            <div class="attendees-sub-title"><?php echo __('Add the names of attendees for this course below')?></div>

            <div class="attendees-name"></div>
            <div class="error-message"></div>

            <button type="button" title="<?php echo __('Save and book') ?>" class="submit sys_save_and_book">
                <span><span><?php echo __('Save and book') ?></span></span>
            </button>

        </div>
    </div>
</div>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            $(".fake-book-now").click(function(){
                var qty = parseInt($('.product-options-bottom .field.qty .control input#qty').val());
                var availableqty = parseInt($('input.product-custom-option:checked', '#product_addtocart_form').parent().find(".spaces-remaining .count").text());
                if (qty){
                    if (qty > availableqty){
                        $('#add-attendees-popup .attendees-title').hide();
                        $('#add-attendees-popup .attendees-sub-title').hide();
                        $('#add-attendees-popup .attendees-name').hide();
                        $('#add-attendees-popup .sys_save_and_book').hide();
                        $('#add-attendees-popup .error-message').text('We don\'t have as many spaces as you requested');
                    } else {
                        $('#add-attendees-popup .attendees-title').show();
                        $('#add-attendees-popup .attendees-sub-title').show();
                        $('#add-attendees-popup .attendees-name').show();
                        $('#add-attendees-popup .sys_save_and_book').show();
                        $('#add-attendees-popup .error-message').empty();
                        $( "div.attendees-name" ).empty();
                        var i;
                        for (i = 0; i < qty; i++) {
                            $( "div.attendees-name" ).append( "<input class='sys_input_class' type='text'>" );
                        }
                    }
                    var options = {
                        type: 'popup',
                        modalClass:'add-attendees-popup',
                        buttons: []
                    };
                    var popup = modal(options, $('#add-attendees-popup'));
                    $('#add-attendees-popup').modal('openModal');
                } else {
                    $('#product-addtocart-button').trigger('click');
                }

            });

            $("body").on( "click",'.sys_save_and_book', function(e) {
                var params = '';
                $('input.sys_input_class').each(function (e) {

                    if (!$(this).val()){
                        $('.attendees-popup-content .error-message').text('Please fill in all fields');
                        e.preventDefault();
                    }

                    params += $(this).val()+', ';
                });

                $('.product-options-bottom .box-tocart input[name=attendees]').attr('value', params.slice(0,-2)).trigger('change');

                $('#add-attendees-popup').modal('closeModal');
                $('#product-addtocart-button').trigger('click');
            });

        }
    );
</script>
