<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
switch ($type = $block->getType()) {

    case 'related':
        /** @var \Magento\Catalog\Block\Product\ProductList\Related $block */
        if ($exist = $block->getItems()->getSize()) {
            $type  = 'related';
            $class = $type;

            $image             = 'related_products_list';
            $title             = __('featured courses');
            $items             = $block->getItems();
            $limit             = 0;
            $shuffle           = 0;
            $canItemsAddToCart = $block->canItemsAddToCart();

            $showAddTo    = true;
            $showCart     = true;
            $templateType = null;
            $description  = false;
        }
        break;

    default:
        $exist = null;
}
?>


<?php if ($exist):?>
<div class="block <?= /* @escapeNotVerified */ $class ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?= /* @escapeNotVerified */ $limit ?>" data-shuffle="<?= /* @escapeNotVerified */ $shuffle ?>">

    <div class="block-title title">
        <strong id="block-<?= /* @escapeNotVerified */ $class ?>-heading" role="heading" aria-level="2"><?= /* @escapeNotVerified */ $title ?></strong>
    </div>

    <div class="products wrapper grid products-grid products-<?= /* @escapeNotVerified */ $type ?>">
        <ol class="products list items product-items">
            <?php foreach ($items as $_item): ?>
                <li class="item product product-item">
                    <div class="product details product-item-details">
                        <div class="row">
                            <div class="date calendar">
                                <span class="day">01</span>
                                <span class="month">Jan</span>
                            </div>
                            <strong class="product name product-item-name"><a class="product-item-link" title="<?= $block->escapeHtml($_item->getName()) ?>" href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                                    <?= $block->escapeHtml($_item->getName()) ?></a>
                            </strong>
                        </div>

                        <div class="row">
                            <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">Read more</a>

                            <?php if ($showCart): ?>
                                <?php if ($showCart): ?>
                                    <div class="actions-primary">
                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                            <button class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?= /* @escapeNotVerified */ __('Book') ?>">
                                                <span><?= /* @escapeNotVerified */ __('Book') ?></span>
                                            </button>
                                        <?php else: ?>
                                            <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                            ?>
                                            <button class="action tocart primary"
                                                    data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                    type="button" title="<?= /* @escapeNotVerified */ __('Book') ?>">
                                                <span><?= /* @escapeNotVerified */ __('Book') ?></span>
                                            </button>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>

                    </div>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>
</div>
<?php endif; ?>
