<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
/** @var \Magento\Contact\Block\ContactForm $block */
?>
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field note no-label"><?= $block->escapeHtml(__('We’d love to hear from you! If you have any queries about Target Training Associates services or its courses, have a training need or you would like more information, simply contact us on the details below:')) ?></div>
        <h3><?= $block->escapeHtml(__('submit YOUR Questions')) ?></h3>
        <div class="fields">
            <div class="field name required">
                <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                <div class="control">
                    <input name="name" id="name" placeholder="<?= $block->escapeHtml(__('Your name *')) ?>" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('name') ?: $this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input name="email" id="email" placeholder="<?= $block->escapeHtml(__('Email address*')) ?>" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('email') ?: $this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="field telephone">
                <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                <div class="control">
                    <input name="telephone" id="telephone" placeholder="<?= $block->escapeHtml(__('Enter your phone…')) ?>" title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>" value="<?= $block->escapeHtmlAttr($this->helper('Magento\Contact\Helper\Data')->getPostValue('telephone')) ?>" class="input-text" type="text" />
                </div>
            </div>
        </div>
        <div class="field comment required">
            <label class="label" for="comment"><span><?= $block->escapeHtml(__('What’s on your mind?')) ?></span></label>
            <div class="control">
                <textarea name="comment" id="comment" placeholder="<?= $block->escapeHtml(__('Message')) ?>" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"><?= $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getPostValue('comment')) ?></textarea>
            </div>
        </div>
    </fieldset>
    <?= $block->getChildHtml('form.additional.info') ?>

    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>



<div class="contact-static">
    <div class="contact-info">
        <div class="contact-phone-email">
            <h3>Contact details:</h3>
            <p>Phone: <a href="tel:0800 302 9344">0800 302 9344</a></p>
            <p>Email: <a href="mailto:info@targettrg.co.uk">info@targettrg.co.uk</a></p>
        </div>
        <div class="contact-address">
            <h3>By post:</h3>
            <p>Target Training Associates <br /> 107 Cheapside, London. EC2V 6DN</p>
        </div>
        <div class="contact-social">
            <h3>Follow us:</h3>
            <ul>
                <li><a href="https://www.facebook.com/TargetTrgAssociates/" target="_blank"><img src="https://targettrg.co.uk/static/frontend/targettraining/default/en_GB/images/fb_footer.png" /></a></li>
                <li><a href="https://www.linkedin.com/company/target-training-associates-ltd/" target="_blank"><img src="https://targettrg.co.uk/static/frontend/targettraining/default/en_GB/images/in_footer.png" /></a></li>
                <li><a href="https://twitter.com/targettrgassoc" target="_blank"><img src="https://targettrg.co.uk/static/frontend/targettraining/default/en_GB/images/tw_footer.png" /></a></li>
            </ul>
        </div>
    </div>
    <div class="contact-map"><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2482.947057598219!2d-0.09570258427222145!3d51.51418727963618!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4876035559fbd093%3A0x366df7fecab1a53f!2s107%20Cheapside%2C%20London%20EC2V%206DN!5e0!3m2!1sen!2suk!4v1569424906578!5m2!1sen!2suk" width="320" height="240" frameborder="0" style="border:0;" allowfullscreen=""></iframe></div>
</div>